[project]
name = "IDS"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.0,<3.13"
redis-server = ">=7.2.3,<7.3"
redis-py = ">=5.0.1,<5.1"
numpy = ">=1.26.2,<1.27"
jupyterlab = ">=4.0.9,<4.1"
