[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "redis-IDS-lab"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
python = ">=3.12.6,<4"
redis-py = ">=5.0.9,<6"
numpy = ">=2.1.1,<3"
jupyterlab = ">=4.2.5,<5"
marimo = ">=0.9.12,<0.10"
pandas = ">=2.2.3,<3"

[feature.server] # redis-cli is only available with server, hence on Linux :(
platforms = ["linux-64"]

[feature.server.dependencies]
redis-server = ">=7.4.0,<8"

[feature.server.tasks]
serve = "redis-server"

[environments]
server = ["server"]
